### PR TITLE
Fix module routing in RouterFactory

### PR DESCRIPTION
**Pull request by pilarik31**
Hi,

looks like currently, module routing is broken.
Fixed that by adding `<module>` to the mask.

### CODE REVIEW

**Comment by dg** [comment]
What exactly was broken?

**Comment by pilarik31** [comment]
[Nette is looking](https://i.imgur.com/oRXSyJi.png) for Admin presenter at `App\Module\Presenters\AdminPresenter`, which is incorrect, since that presenter is now in `App\Module\Admin\Presenters\AdminPresenter`.

With `<module>` in the mask, it finds the presenter, and correctly redirects me to login, if I'm not logged in.

Also, without the module in the mask, the index is trying to do some [weird URL](https://i.imgur.com/m4P7315.png).

**Comment by dg** [comment]
I see. And the URL `/admin/dashboard` is mentioned where, in the documentation?

**Comment by pilarik31** [comment]
There aren't any specific URLs in the repo's readme, so I just looked at the old commit, before implementation of modules, and it worked like:
- `/sign/*` - SignPresenter
- `/` - DashboardPresenter

And with the modules stucture, that broke.

**Comment by dg** [comment]
Yes, url has changed but I still don't understand why it is broken… This seems more like feature request.

**Comment by pilarik31** [comment]
In the current state, I can't get it to work at all.
Clean install from the repository, following the installation guide, is resulting in [this](https://i.imgur.com/m4P7315.png) malformed URL.

**Comment by dg** [comment]
I understand now. It looks like the built-in PHP server has a "feature" that when there is a dot in the URL, it doesn't work properly https://bugs.php.net/bug.php?id=61286

**Pull request closed without merging**
